name: Integration
on:
  pull_request:
    branches:
      - main

jobs:
  merge_action:
    name: Analyze commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'
          channel: "stable"
      - run: flutter --version
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter analyze
